export const baseUrl = 'http://devserver.mindnerves.com:8572';
export const token =
  'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huQGdtYWlsLmNvbSIsImV4cCI6MTczMzg4OTU5NywiYXV0aCI6IlJPTEVfVVNFUiIsImlhdCI6MTcyNjExMzU5N30.BUWS3DhS41V-pS-pknzzvsCY3OXa6ZE9w7THEsUWWjvZq7fYGfcmyds5HFVQp1pCbkABi-AB_GRM18wlEbrgXg'
